### ISSUE TITLE
mashlib recipe with subdomain configuration

### ISSUE THREAD

**Issue by bourgeoa** [CommunitySolidServer/Recipes#31] opened 2023-11-15 21:06 UTC
I'm able to create an account.
- But when I click on the webid I got the following error

  GET `http://bourgeoa.localhost:3000/profile/card` net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
  
- when I click to the pod link. I got these 2 following errors
  - (index):89 
        
        
       GET http://bourgeoa.localhost:3000/.account/ 401 (Unauthorized)
(anonymous) @ (index):89
(anonymous) @ (index):98
  - (index):92 
        
        
       GET http://bourgeoa.localhost:3000/undefined 401 (Unauthorized)

```
{
    "@context": [
      "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^7.0.0/components/context.jsonld"
    ],
    "import": [
      "css:config/app/init/static-root.json",
      "css:config/app/main/default.json",
      "css:config/app/variables/default.json",
      "css:config/http/handler/default.json",
      "css:config/http/middleware/default.json",
      "css:config/http/notifications/all.json",
      "css:config/http/server-factory/http.json",
      "css:config/http/static/default.json",
      "css:config/identity/access/public.json",
      "css:config/identity/email/default.json",
      "css:config/identity/handler/default.json",
      "css:config/identity/oidc/default.json",
      "css:config/identity/ownership/token.json",
      "css:config/identity/pod/static.json",
      "css:config/ldp/authentication/dpop-bearer.json",
      "css:config/ldp/authorization/webacl.json",
      "css:config/ldp/handler/default.json",
      "css:config/ldp/metadata-parser/default.json",
      "css:config/ldp/metadata-writer/default.json",
      "css:config/ldp/modes/default.json",
      "css:config/storage/backend/file.json",
      "css:config/storage/key-value/resource-store.json",
      "css:config/storage/location/pod.json",
      "css:config/storage/middleware/default.json",
      "css:config/util/auxiliary/acl.json",
      "css:config/util/identifiers/suffix.json",
      "css:config/util/logging/winston.json",
      "css:config/util/representation-conversion/default.json",
      "css:config/util/resource-locker/file.json",
      "css:config/util/variables/default.json"
    ],
    "@graph": [
      {
        "comment": [
          "A filesystem-based server with Databrowser as UI.",
          "Derived from config/file-no-setup.json"
        ]
      },
      {
        "comment": "Serve Databrowser as default representation",
        "@id": "urn:solid-server:default:DefaultUiConverter",
        "@type": "ConstantConverter",
        "contentType": "text/html",
        "filePath": "./node_modules/mashlib/dist/databrowser.html",
        "options_container": true,
        "options_document": true,
        "options_minQuality": 1,
        "options_disabledMediaRanges": [
          "image/*",
          "application/pdf"
        ]
      },
      {
        "comment": "Serve Mashlib static files.",
        "@id": "urn:solid-server:default:StaticAssetHandler",
        "@type": "StaticAssetHandler",
        "assets": [
          {
            "@type": "StaticAssetEntry",
            "relativeUrl": "/mash.css",
            "filePath": "./node_modules/mashlib/dist/mash.css"
          },
          {
            "@type": "StaticAssetEntry",
            "relativeUrl": "/mashlib.min.js",
            "filePath": "./node_modules/mashlib/dist/mashlib.min.js"
          },
          {
            "@type": "StaticAssetEntry",
            "relativeUrl": "/mashlib.min.js.map",
            "filePath": "./node_modules/mashlib/dist/mashlib.min.js.map"
          }
        ]
      }
    ]
  }
```

There is no issue with suffix configuration.

**Comment by joachimvh** [comment] 2023-11-16 09:34
There are 2 problems here.

The fact that the page on the root pod has problems with the links on it is a CSS issue. You're actually not even supposed to see that page when going to the root pod, only on the root of the server. You should see the root contents of the pod when going to it. This is an issue with the logic used for static files where it doesn't take the subdomain into account. I'll look into fixing that for CSS, but for now that means the `static-root` option does not work with subdomains.

I'm not exactly sure why accessing the WebID doesn't work though. I can confirm that it also doesn't work when I try it, although I get a different error. For me the error occurs on this line because `node` is `null` instead of a defined value: https://github.com/SolidOS/solid-ui/blob/ee8e69c20cc21d93eb942bc5479e4644d5704964/src/utils/index.js#L250. How data is accessed hasn't changed much in v7 and I don't know anything about the solid-ui code there so I can't immediately comment what would be an issue there.

**Comment by joachimvh** [comment] 2023-11-16 09:39
Well to amend the previous reply, it's not that the server completely doesn't work with the `static-root` option, it's just that the page shown in the root of a pod will contain URLs that won't work. You can still login to your account by manually going to `http://localhost:3000/.account/` instead of `http://bourgeoa.localhost:3000/.account/`.

**Comment by joachimvh** [comment] 2023-11-16 10:23
Can I ask why you want to use the `static-root` option with subdomain pods? That option was mostly designed for the suffix case, which is why I forgot about subdomains, as in that case you are not allowed to put data in the root of the server, so this gets around that. For subdomains this is less relevant as there you should be able to put data in both the server root and the pods.

**Comment by bourgeoa** [comment] 2023-11-16 11:19
> Can I ask why you want to use the `static-root` option with subdomain pods?

There was no reason. I did not think about it. It was the default in configurator.

**Comment by joachimvh** [comment] 2023-11-16 11:33
> There was no reason. I did not think about it. It was the default in configurator.

Good to know. Best solution might be to just disable that combination in the configurator then.

**Comment by bourgeoa** [comment] 2023-11-16 12:27
In between what option shall I use ?

**Comment by joachimvh** [comment] 2023-11-16 12:41
So to be clear, in the configuration generator this is about the "Miscellaneous -> Initialize root" option. If you want to have an HTML document at the root, which I'm assuming you do, the "Accessible root" option probably does what you want. You would then have to update the ACL file in the root to make sure only you have write access there as by default it provides full access. You can then also put an `index.html` file in the root, which will be displayed when someone accesses the root through the browser.

**Comment by bourgeoa** [comment] 2023-11-16 17:01
I used the `accessible root` option and have add some improvement but still cannot login
THis is the message window
```
bourgeoa.localhost:3000 indique

Client registration failed: [Error: Dynamic Registration could not be completed because the issuer has no registration endpoint.]
```
The errors are 
```
GET http://bourgeoa.localhost:3000/common/css/bootstrap.min.css net::ERR_ABORTED 401 (Unauthorized)
(anonymous) @ manager.js:991
Promise.then (async)
R.propertyTable @ manager.js:970
c @ manager.js:1959
u @ manager.js:2017
e.fireCallbacks @ utils-js.js:65
value @ fetcher.js:1088
value @ fetcher.js:485
(anonymous) @ fetcher.js:1720
Promise.then (async)
value @ fetcher.js:1718
(anonymous) @ fetcher.js:863
Promise.then (async)
value @ fetcher.js:862
(anonymous) @ fetcher.js:719
f @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ fetcher.js:739
value @ fetcher.js:690
value @ fetcher.js:936
ee @ manager.js:2052
GotoSubject @ manager.js:2181
(anonymous) @ index.js:27
p @ index.js:11
(anonymous) @ index.js:11
(anonymous) @ index.js:11
l @ index.js:12
a @ index.js:13
(anonymous) @ index.js:13
(anonymous) @ index.js:13
u @ index.js:40
t.default @ index.js:15
(anonymous) @ index.ts:38
Promise.then (async)
c.panes.runDataBrowser @ index.ts:37
(anonymous) @ (index):2
IssuerConfigFetcher.js:111 
        
        
       GET http://bourgeoa.localhost:3000/.well-known/openid-configuration 401 (Unauthorized)
fetchConfig @ IssuerConfigFetcher.js:111
handle @ OidcLoginHandler.js:27
login @ ClientAuthentication.js:20
await in login (async)
login @ Session.js:37
(anonymous) @ login.js:671
f @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
t @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ login.js:689
(anonymous) @ login.js:734
```

It looks like I can login in root (localhost:3000), but not in bourgeoa.localhost:3000

**Comment by bourgeoa** [comment] 2023-11-16 17:47
- Just for information, I run a v5 without any problem at `https://solidcommunity.net:3000`, never tried a v6.

-   Just found a different file structure for `.internal` location in v5 and v7
    - in v5 I have .internal only in `data/www`
    - in v7 I have 2 `.internal` one  in `data` and an other one in `data/www`

**Comment by joachimvh** [comment] 2023-11-17 09:23
I'm not sure how this worked in the v5 release. I just tried it out there and it gives the same error. It is also expected behaviour. The URL of the IDP is the base URL, so `http://localhost:3000`. That is also the URl the WebID will reference using the `solid:oidcProvider` triple and is where the authentication client should send its request to.

> * Just found a different file structure for `.internal` location in v5 and v7

That is indeed a bug, but should have no major impact. It's just the locks being stored in a different location than the other internal data.



> * But when I click on the webid I got the following error
>       GET `http://bourgeoa.localhost:3000/profile/card` net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

I've had another look at this and I think I found the issue in CSS. Since v7 the server now also outputs the content-length. But in the case when configuring the server to return the mashlib HTML page instead of the resource that content length will be wrong as the original resource is not returned. I'll look into fixing this which should resolve the WebID issue.

**Comment by joachimvh** [comment] 2023-11-17 10:08
> > * But when I click on the webid I got the following error
> >   GET `http://bourgeoa.localhost:3000/profile/card` net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
> 
> I've had another look at this and I think I found the issue in CSS. Since v7 the server now also outputs the content-length. But in the case when configuring the server to return the mashlib HTML page instead of the resource that content length will be wrong as the original resource is not returned. I'll look into fixing this which should resolve the WebID issue.

The fix in https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1781 makes it so the WebID (and other resources) are accessible again. Will look into merging this and doing a new release soon.

**Comment by joachimvh** [comment] 2023-11-20 09:05
The fix mentioned above is part of release v7.0.2.

**Comment by bourgeoa** [comment] 2023-11-20 17:23
Tested v7.0.2 and access to /profile/card is working.

After pod creation, login does not give any authenticated access to pod  content 
`PUT http://bourgeoa.localhost:3000/profile/card 401 (Unauthorized)`

**Comment by joachimvh** [comment] 2023-11-21 08:08
> `The webid claim to be an HTTPS URI or a localhost with port number HTTP URI`

This is the cause of the issue. When using DPoP authentication you need to use a HTTPS URLs. The parsing library does also support using an HTTP URL if it is a `localhost` URL for debugging purposes, but it does not support subdomains of localhost. 

It seems a fix was made to the library to also support this: https://github.com/CommunitySolidServer/access-token-verifier/pull/236. But there never was a release afterwards. Will have to see if it is possible to have a new release there. Until there is a new release there the solution would be to run the server as HTTPS.

**Comment by bourgeoa** [comment] 2023-11-21 17:45
> It seems a fix was made to the library to also support this: [CommunitySolidServer/access-token-verifier#236](https://github.com/CommunitySolidServer/access-token-verifier/pull/236). But there never was a release afterwards. Will have to see if it is possible to have a new release there. Until there is a new release there the solution would be to run the server as HTTPS.

So I tried to run the server as HTTPS.
Now the issue is 
```
2023-11-21T17:40:09.796Z [DPoPWebIdExtractor] {Primary} warn: Error verifying WebID via DPoP-bound access token: The WebID could not be dereferenced.
Actual: https://bourgeoa.localhost:3000/profile/card#me
Expected: A dereferenceable resource
```

**Comment by joachimvh** [comment] 2023-11-22 09:29
I spent some time looking into this as this should work. Conclusion is that the problems all mostly stem from the fact that it's being tested on localhost which complicates some things.

I'm not sure which problems you might have so I'm going to cover all those I ran into.

The problem with using a subdomain in localhost is that `fetch` is not going to find it as only `localhost` is defined in the host file. So the host file needs to be extended with `127.0.0.1       bourgeoa.localhost`. I'm not sure why browsers didn't have an issue accessing a subdomain of localhost. I didn't look into this but I guess they are smart enough to take those into account.

You will probably not have this issue, but I was using an old certificate which was expired so I had to generate a new one.

By default, fetch requests will also fail on self-signed certificates. Node.js has an env variable that can be set to get around that for debugging purposes though. So I changed the `start` script in the `package.json` to `set NODE_TLS_REJECT_UNAUTHORIZED=0&& npx community-solid-server -c config-mashlib.json` (I'm on Windows).

After that the profile container can be accessed after logging in and the WebID can be modified.

Since the access token library doesn't print what actually went wrong I edited the file in `node_modules/@solid/access-token-verifier/dist/algorithm/retrieveWebidTrustedOidcIssuers.ts` to print the error thrown [here](https://github.com/CommunitySolidServer/access-token-verifier/blob/01a311bd95b1963226520026df5867fa89a22d97/src/algorithm/retrieveWebidTrustedOidcIssuers.ts#L18) to figure out what was going wrong.

**Comment by bourgeoa** [comment] 2023-11-22 11:47
Thanks for your detailed tests and explanation.
Sorry it does not work for me. I suppose I'm having a wrong parameter.

Can you share your config ?

This is mine :
```
    "start": "NODE_TLS_REJECT_UNAUTHORIZED=0&& npx community-solid-server -c ./config/https-mashlib-subdomain-file.json -f ./data --httpsKey ../privkey.pem --httpsCert ../fullchain.pem -b https://localhost:3000",

```
```
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^7.0.0/components/context.jsonld"
  ],
  "import": [
    "css:config/app/init/default.json",
    "css:config/app/main/default.json",
    "css:config/app/variables/default.json",
    "css:config/http/handler/default.json",
    "css:config/http/middleware/default.json",
    "css:config/http/notifications/all.json",
    "css:config/http/server-factory/https.json",
    "css:config/http/static/default.json",
    "css:config/identity/access/public.json",
    "css:config/identity/email/example.json",
    "css:config/identity/handler/default.json",
    "css:config/identity/oidc/default.json",
    "css:config/identity/ownership/token.json",
    "css:config/identity/pod/static.json",
    "css:config/ldp/authentication/dpop-bearer.json",
    "css:config/ldp/authorization/webacl.json",
    "css:config/ldp/handler/default.json",
    "css:config/ldp/metadata-parser/default.json",
    "css:config/ldp/metadata-writer/default.json",
    "css:config/ldp/modes/default.json",
    "css:config/storage/backend/file.json",
    "css:config/storage/key-value/resource-store.json",
    "css:config/storage/location/pod.json",
    "css:config/storage/middleware/default.json",
    "css:config/util/auxiliary/acl.json",
    "css:config/util/identifiers/subdomain.json",
    "css:config/util/logging/winston.json",
    "css:config/util/representation-conversion/default.json",
    "css:config/util/resource-locker/file.json",
    "css:config/util/variables/default.json"
  ],
  "@graph": [
    {
      "comment": "The settings of your email server.",
      "@type": "Override",
      "overrideInstance": {
        "@id": "urn:solid-server:default:EmailSender"
      },
      "overrideParameters": {
        "@type": "BaseEmailSender",
        "senderName": "Community Solid Server <solid@example.email>",
        "emailConfig_host": "smtp.example.email",
        "emailConfig_port": 587,
        "emailConfig_auth_user": "solid@example.email",
        "emailConfig_auth_pass": "NYEaCsqV7aVStRCbmC"
      }
    },
    {
      "comment": "The location of the new pod templates folder.",
      "@type": "Override",
      "overrideInstance": {
        "@id": "urn:solid-server:default:PodResourcesGenerator"
      },
      "overrideParameters": {
        "@type": "StaticFolderGenerator",
        "templateFolder": "@css:templates/pod"
      }
    },
    {
      "comment": "Where the WebID is located in the generated pod, relative to the root.",
      "@type": "Override",
      "overrideInstance": {
        "@id": "urn:solid-server:default:PodCreator"
      },
      "overrideParameters": {
        "@type": "BasePodCreator",
        "relativeWebIdPath": "profile/card#me"
      }
    },
    {
      "comment": [
        "A filesystem-based server with Databrowser as UI.",
        "Derived from config/file-no-setup.json"
      ]
    },
    {
      "comment": "Serve Databrowser as default representation",
      "@id": "urn:solid-server:default:DefaultUiConverter",
      "@type": "ConstantConverter",
      "contentType": "text/html",
      "filePath": "./node_modules/mashlib/dist/databrowser.html",
      "options_container": true,
      "options_document": true,
      "options_minQuality": 1,
      "options_disabledMediaRanges": [
        "image/*",
        "application/pdf"
      ]
    },
    {
      "comment": "Serve Mashlib static files.",
      "@id": "urn:solid-server:default:StaticAssetHandler",
      "@type": "StaticAssetHandler",
      "assets": [
        {
          "@type": "StaticAssetEntry",
          "relativeUrl": "/mash.css",
          "filePath": "./node_modules/mashlib/dist/mash.css"
        },
        {
          "@type": "StaticAssetEntry",
          "relativeUrl": "/mashlib.min.js",
          "filePath": "./node_modules/mashlib/dist/mashlib.min.js"
        },
        {
          "@type": "StaticAssetEntry",
          "relativeUrl": "/mashlib.min.js.map",
          "filePath": "./node_modules/mashlib/dist/mashlib.min.js.map"
        }
      ]
    }
  ]
}

```

**Comment by bourgeoa** [comment] 2023-11-22 12:01
To print the error what did you put in `node_modules/@solid/access-token-verifier/dist/algorithm/retrieveWebidTrustedOidcIssuers.js`

**Comment by joachimvh** [comment] 2023-11-22 12:22
The only difference in my config was the the email setting was disabled, which should not impact this.

To have the fetch error logged, insert `console.error(e);` at line 22 of that file. So in the catch block of `dereferenceWebid`. Knowing what the error is would indeed help finding out what the remaining issue is.

If you copy/pasted exactly what you did I think the problem is your start script. You wrote `"start": "NODE_TLS_REJECT_UNAUTHORIZED=0&& npx...`, but it should be `"start": "set NODE_TLS_REJECT_UNAUTHORIZED=0&& npx...` on Windows or `"start": "NODE_TLS_REJECT_UNAUTHORIZED=0 npx...` on Unix.

**Comment by bourgeoa** [comment] 2023-11-22 16:00
The printed error seems to be : 
```
2023-11-22T15:59:12.145Z [PermissionBasedAuthorizer] {Primary} warn: Unauthenticated agent has no read permissions
2023-11-22T15:59:12.169Z [HandlerServerConfigurator] {Primary} info: Received GET request for /
FetchError: request to https://bourgeoa.localhost:3000/profile/card#me failed, reason: getaddrinfo ENOTFOUND bourgeoa.localhost
    at ClientRequest.<anonymous> (/mnt/d/github/source/workspaces/css-mashlib/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
2023-11-22T15:59:12.196Z [DPoPWebIdExtractor] {Primary} warn: Error verifying WebID via DPoP-bound access token: The WebID could not be dereferenced.
Actual: https://bourgeoa.localhost:3000/profile/card#me
Expected: A dereferenceable resource
2023-11-22T15:59:12.198Z [WebAclReader] {Primary} info: Found applicable ACL document https://bourgeoa.localhost:3000/.acl```

**Comment by joachimvh** [comment] 2023-11-22 16:07
I fixed the `ENOTFOUND` error by updating the host file. Did you add `127.0.0.1       bourgeoa.localhost`? Either in `c:\Windows\System32\Drivers\etc\hosts` or `/etc/hosts` depending on OS.

**Comment by bourgeoa** [comment] 2023-11-22 16:21
This is my `/etc/hosts`
```
root@DESKTOP-PIRJOCS:/mnt/d/github/source/workspaces/css-mashlib# cat /etc/hosts
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateHosts = false
127.0.0.1       localhost
127.0.1.1       DESKTOP-PIRJOCS.        DESKTOP-PIRJOCS
﻿
127.0.0.1       nic.localhost
127.0.0.1       tim.localhost
127.0.0.1       nicola.localhost
100.74.40.71    dsx
192.168.68.100  host.docker.internal
192.168.68.100  gateway.docker.internal
127.0.0.1       kubernetes.docker.internal

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by bourgeoa** [comment] 2023-11-22 16:36
> The problem with using a subdomain in localhost is that `fetch` is not going to find it as only `localhost` is defined in the host file. So the host file needs to be extended with `127.0.0.1 bourgeoa.localhost`. I'm not sure why browsers didn't have an issue accessing a subdomain of localhost. I didn't look into this but I guess they are smart enough to take those into account.

It is working now.
Sorry to have not read your reply correctly.
Thank you for your patience.

> It seems a fix was made to the library to also support this: https://github.com/CommunitySolidServer/access-token-verifier/pull/236. But there never was a release afterwards. Will have to see if it is possible to have a new release there. Until there is a new release there the solution would be to run the server as HTTPS.

Yes it may be easier to run on http://localhost:3000 when doing tests of SolidOS

**Comment by joachimvh** [comment] 2023-11-24 07:38
> It is working now.

Glad to hear you got it working, I'll close the issue then.



> Yes it may be easier to run on http://localhost:3000 when doing tests of SolidOS

Yes I'll look into that. Although the change to the host file will still be required afterwards.

**Closed by joachimvh** 2023-11-24 07:38 UTC

**Comment by joachimvh** [comment] 2024-01-05 10:59
> Yes it may be easier to run on http://localhost:3000 when doing tests of SolidOS

The latest version of the access-token-verifier library includes this change now. So you can make use of it if you reset your package-lock.json file so the new version is used.
